name: Publish Bridge Techdocs

on:
  push:
    branches:
      - 'master'
    paths:
      - '.github/workflows/techdocs.yaml'
      - 'catalog-info.yaml'
      - '**/*.md'
      - 'docs/**'
      - 'mkdocs.yml'
  workflow_dispatch: {}

jobs:
  publish-techdocs:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6
        with:
          repository: get-bridge/developer_portal
          token: ${{ secrets.GIT_HUB_TOKEN }}
          path: .github/developer_portal
          ref: master
      - uses: ./.github/developer_portal/.github/actions/techdocs
        with:
          aws_access_key_id: ${{ secrets.TRUSS_AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.TRUSS_AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-2
          entity_name: 'webhook-tester'
          entity_kind: 'component'
          entity_namespace: 'default'
